language: node_js
node_js:
  - "7"
install:
  - npm install -g codecov
  - npm install
script:
  - npm run lint
  - npm run test -- --browsers PhantomJS --code-coverage true --watch false
  - codecov
