language: node_js
node_js:
  - "7"
install:
  - yarn global add codecov
  - yarn install
script:
  - yarn run lint
  - yarn run test -- --browsers PhantomJS --code-coverage true --watch false
  - codecov
